### ISSUE TITLE
EPIC: new SDK

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-nodejs-sdk#2]
## Preparing

* [x] maxkoryukov/route4me-nodejs-sdk#1 lint rules
* [x] maxkoryukov/route4me-nodejs-sdk#1 test tool
* [x] maxkoryukov/route4me-nodejs-sdk#1 coverage tool
* [x] #17 doc tool (not sure, but seems like with jsdoc this will look much more useful)
* [x] ~#16 browser support~ - will be solved in next version

## Core

* [x] Route4Me - main file
* [x] send request/handle response classes
* [x] Error objects
* [x] logger
* [x] configuration
* [x] ~reuse json-shema~ there is a use-case for testing. Final solution here: #28
* [x] input validator - **disabled** in this package
* [x] output converter

## Methods

* [x] make a decision about Route4Me top-level file architecture (all methods in one class, as in C#, or split methods to sub-objects, for example : `Routes`, `Orders` ...)

Next: implement functionality

* [x] #3 Optimizations
* [x] #4 Routes
* [x] #5 Orders
* [x] #6 Addresses
* [x] #7 Geocoding
* [x] #8 Tracking
* [x] #9 Members
* [x] #10 Notes
* [x] #11 Vehicles
* [x] #12 Activity Feed
* [x] #13 Address Book
* [x] #14 Avoidance Zones
* [x] #15 Territories

**Comment by maxkoryukov** [comment]
Solved in 0.2.0

https://github.com/route4me/route4me-nodejs-sdk/releases/tag/v0.2.0
