### ISSUE TITLE
Refactor documentation (currently, only for NodeJS SDK)

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-nodejs-sdk#26]
Convenient and clear documentation is very important for SDK, bcz the main purpose of SDK - to make it easier to integrate service. If SDK is entangled - nobody want to use it. If SDK is clear - everybody wants to use it;)

There are jsdoc-comments for functions, methods, namespaces...

But right now the documentation is not ready for end-user (SDK user), because this doc doesn't cover all a lot of questions.

## Doc-layout proposal

1. [x] main page (`readme` option in `jsdoc.config` should point to the other file, not the main README)
    * [x] several badges
    * [x] introduction
    * [x] how to read this doc
    * [x] TOC (could be in sep. file, if the `jsdoc` could generate toc automatically)
    * [x] simple example
2. [x] Core object `Route4Me` 
    * [x] description
    * [x] options
    * [x] links to sections (Optimizations, Routes ...)
    * [x] example (how to create)
3. [x] Subsections (Optimizations, Routes, Addresses ... )
    * [x] desctiption
    * [x] methods
    * [x] examples
4. [x] Common objects
    * [x] callback desc
    * [x] all errors
    * [x] Logger
    * [x] Validator
    * ....

All examples should be included to jsdoc.

## Overall requirements

* [x] analytics (google analytics)
* [x] separated TOC is required (**side navigation**), since there are more than 10 methods

## Examples for API

Examples for API **should be written separately**: see #31

**Comment by Olman62** [comment]
Hi Maksim,

Thank you for valuable remarks and findings.

Are you talking about Node.js SDK documentation? As I know JSDoc works with
javascript code.

I'm agree with your opinion about source code documentation - I'll see
where I can improve it myself and I'll send message about this issue to
other programmers.

Regards,
Oleg

**Comment by maxkoryukov** [comment]
@Olman62 , currently, this issue is about JS (I will fix title).

Right now the description of issue is just **a draft** for doc-requirements (for me). As you could see - this ticket is attached to the milestone 1.1.0, but right now I am on version **0.1.8**, and current target - 1.0.0

Currently I have just scraps of the doc, but I am going to reuse this stuff;)

-----

## Current docs

I have published current docs here: https://maxkoryukov.github.io/route4me-nodejs-sdk/

I am sure: if I will ask you to write some code using that documentation - you will stuck))

@Olman62, thank you for review;)

**Comment by maxkoryukov** [comment]
As we previously discussed with Oleg : **gitbook** is a very good tool for documentation.

Pros:

* consume GFM (github flavored markdown)
* have pretty themes (including dark) out of the box, switching on the fly
* allow to export PDF book (and several other book format)
* supports online editing with clever online editor
* sync with github
* external-hosting (need to ensure, that external site looks like gitbook-hosted for end-user)
* Multilingual support!

Cons:

* again : markdown. Not every _autodoc_ tool supports for markdown output (for example, `jsdoc` can't create documentation in `md` format out of the box. Additional tools required)
* tool-belt will include another one tool..   

-------------

### Folder structure

gitbook structure depends on:

1. `SUMMARY.md` - Table of Contents
2. folder structure

So, you are free to use **any** layout for files, **BUT** you must maintain structure in `SUMMARY.md`

It is a cons and pros at the same time.

I hope, there is a plugin for autogenerating `SUMMARY.md`
