### ISSUE TITLE
New Tracking

### ISSUE THREAD

**Issue by maxkoryukov** [route4me/route4me-nodejs-sdk#8]
### Tracking

* [x] FindAsset https://route4me.io/docs/#get-asset-tracking-data
* [x] METHOD https://route4me.io/docs/#get-route-tracking-data
    * [x] Get a device’s last location history (implemented in **ROUTES**)
    * [x] Get a device’s location history from a time range.
* [x] SetGPS https://route4me.io/docs/#insert-route-tracking-data
